// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'chmlfrp_flutter';
  static const String PROJECT_VERSION = '1.2.0+1';
  static const String HARMONYOS_SANS_SC_BLACK = 'HarmonyOS_Sans_SC_Black';
  static const String HARMONYOS_SANS_SC_BOLD = 'HarmonyOS_Sans_SC_Bold';
  static const String HARMONYOS_SANS_SC_LIGHT = 'HarmonyOS_Sans_SC_Light';
  static const String HARMONYOS_SANS_SC_MEDIUM = 'HarmonyOS_Sans_SC_Medium';
  static const String HARMONYOS_SANS_SC_REGULAR = 'HarmonyOS_Sans_SC_Regular';
  static const String HARMONYOS_SANS_SC_THIN = 'HarmonyOS_Sans_SC_Thin';
}
